---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      tags: sleep600
      #    wait_for:
      #      delay: 600
      #      timeout: 0
      wait_for_connection: 
    - name: "install python for Ansible."
      # Your code here
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    # Add more env vars here
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
  

  
    - name: Run multiple commands
      shell: |
       echo -e "\n get node "
       curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
       echo -e "\n install node"
       sudo apt-get install -y nodejs
       echo -e "\n install npm"
       sudo npm install -g npm@latest
       sudo apt install build-essential
       echo -e "\n install pm2"
       sudo npm install pm2 -g
      register: command_output
    - debug:
       var: command_output.stdout_lines  
  roles:
      - configure-server 