---
- name: "update apt packages."
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

#- name: Install the gpg key for nodejs LTS
#  apt_key:
#   url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
#   state: present

#- name: Install the nodejs LTS repos
#  apt_repository:
#   repo: "deb https://deb.nodesource.com/setup_14.x xenial main"
#   state: present
#   update_cache: yes

#- name: Install the nodejs
#  apt:
#   name: nodejs
#   state: present
- name: Run multiple commands
  shell: |
    # Uninstall viaPackage installed nodejs version
    sudo apt-get remove --purge nodejs

    # Choose your version / architecture
    # Find available versions list there:
    # https://nodejs.org/en/download/releases/

    VERSION=v13.8.0
    DISTRO=linux-x64

    # Download
    wget https://nodejs.org/download/release/v13.8.0/node-v13.8.0-linux-x64.tar.xz

    # Install ie extract archive to /usr/local/lib/nodejs
    sudo mkdir -p /usr/local/lib/nodejs
    sudo tar -xJvf node-$VERSION-$DISTRO.tar.xz -C /usr/local/lib/nodejs 

    # Create symlinks
    sudo ln -s /usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin/node /usr/bin/node
    sudo ln -s /usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin/npm /usr/bin/npm
    sudo ln -s /usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin/npx /usr/bin/npx

    # Update profile
    tee -a ~/.profile << ENDap
    # Nodejs
    VERSION=v13.8.0
    DISTRO=linux-x64
    export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH
    ENDap
    . ~/.profile

    # Tests
    echo  node -v
    echo npm version
    echo npx -v

    sudo npm install pm2 -g
    #npx pm2 start
    #export PATH=/usr/local/lib/nodejs/node-v13.8.0-linux-x64/bin:$PATH
    #npx pm2 start
    #echo pm2 -v

 

#
 #- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: latest
