---
- name: "update apt packages."
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

#- name: Install nvm
#  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v0.33.11
#  tags: nvm

#- name: Source nvm in ~/.{{ item }}
#  lineinfile: >
#      dest=~/.{{ item }}
 #     line="source ~/.nvm/nvm.sh"
#      create=yes
#  tags: nvm
#  with_items:
#    - bashrc
#    - profile 
#- name: Install node and set version
#  become: true
##  become_user: root
#  shell: "source /root/.nvm/nvm.sh && nvm install 13.8.0" 
#  args:
#    executable: /bin/bash

#- name: pm2 
#  become: true
#  become_user: root 
#  shell: |
#    npm install pm2 -g

- name: Run multiple commands
  become: true
  shell: | 
    curl "https://raw.githubusercontent.com/creationix/nvm/master/install.sh" | bash 
    source ~/.bashrc  
    nvm install 13.8.0
    npm install pm2 -g

  
#- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs:13.8.0", "npm"]
#    state: present
#    update_cache: yes

##- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: latest
