---
- name: "update apt packages."
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

#- name: Install the gpg key for nodejs LTS
#  apt_key:
#   url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
#   state: present

#- name: Install the nodejs LTS repos
#  apt_repository:
#   repo: "deb https://deb.nodesource.com/setup_14.x xenial main"
#   state: present
#   update_cache: yes

- name: "nvm"
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "/home/ubuntu"
    creates: "/home/ubuntu/.nvm/nvm.sh"

- name: "node"
  shell: >
    . /home/ubuntu/.nvm/nvm.sh && nvm install 13.8.0
  args:
    executable: /bin/bash
    chdir: "/home/ubuntu"
    creates: "/home/ubuntu/.nvm/versions/{{ item }}"
  loop:
    - node
 
#   name: nodejs
#   state: present
#- name: Run multiple commands
#  shell: |
    #curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    #sudo apt-get install -y nodejs
    #sudo npm install -g npm@latest
    #sudo apt install build-essential -y
    #sudo npm install pm2 -g

    #curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
    #source ~/.bashrc 
    #nvm install 13.8.0  
    #sudo npm install pm2 -g
 #- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: latest
