---
- name: "update apt packages."
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

#- name: Install the gpg key for nodejs LTS
#  apt_key:
#   url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
#   state: present

#- name: Install the nodejs LTS repos
#  apt_repository:
#   repo: "deb https://deb.nodesource.com/setup_14.x xenial main"
#   state: present
#   update_cache: yes

#- name: Install the nodejs
#  apt:
#   name: nodejs
#   state: present
- name: Run multiple commands
  shell: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    source ~/.bashrc
    echo nvm --version
    nvm install 13.8.0
    npm install pm2 -g 

 #- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: latest
