---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes


- name: Run multiple commands
  shell: |
       echo -e "\n get node "
       curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
       echo -e "\n install node"
       sudo apt-get install -y nodejs
       echo -e "\n install npm"
       sudo npm install -g npm@latest
       sudo apt install build-essential
       echo -e "\n install pm2"
       sudo npm install pm2 -g
  register: command_output
- debug:
       var: command_output.stdout_lines #- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: latest
