---
- name: "update apt packages."
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

 

- name: Run multiple commands
  shell: |

      sudo apt install curl
      curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
      source ~/.bashrc  
      nvm install 13.8.0
      sudo npm install pm2 -g

  
 #- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: latest
