version: 2.1
orbs:
  slack: circleci/slack@4.9.3 
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var 
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "CI fail ...",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: fail   
          #s    
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
            #npm install oauth-sign@^0.9.0
      - slack/notify:
           event: pass
           template: basic_success_1
      - slack/notify:
           event: fail
           template: basic_fail_1
  build-backend:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - slack/notify:
           event: pass
           template: basic_success_1
      - slack/notify:
           event: fail
           template: basic_fail_1           
  test-frontend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here       
      - checkout
      - run:
          name: Front-end build
          command: |
            cd frontend
            npm install
            npm run test
      - slack/notify:
           event: pass
           template: basic_success_1
      - slack/notify:
           event: fail
           template: basic_fail_1             
  test-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here       
      - checkout
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run test 
      - slack/notify:
           event: pass
           template: basic_success_1
      - slack/notify:
           event: fail
           template: basic_fail_1        
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - run:
          name: Front-end scan
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack/notify:
           event: pass
           template: basic_success_1
      - slack/notify:
           event: fail
           template: basic_fail_1  
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - run:
          name: Back-end scan
          command: |
            cd backend
            npm install
            npm install oauth-sign@^0.9.0
            #npm audit fix --audit-level=critical --force
            
            #npm audit fix --force
            #npm audit --audit-level=critical
            npm audit fix --force --production
            #fgfsdga
            npm audit --audit-level=none
      - slack/notify:
           event: pass
           template: basic_success_1
      - slack/notify:
           event: fail
           template: basic_fail_1  
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires : [build-frontend]
      - test-backend:  
          requires : [build-backend]  
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]    
  send-notification:
    jobs:
      - notify:
          
          context: slack-secrets        